[build]
  functions = "netlify/functions"
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/journal"
  to = "/journal.html"
  status = 200

[[redirects]]
  from = "/algo"
  to = "/algo.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/options-engine"
  to = "/options-engine.html"
  status = 200

[[redirects]]
  from = "/auth"
  to = "/auth.html"
  status = 200
